# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

user1 = User.create(username: 'Dylan', email: 'dylan@me.com', password: 'dylanpass')
user2 = User.create(username: 'Elise', email: 'elise@me.com', password: 'elisepass')
user3 = User.create(username: 'April', email: 'april@me.com', password: 'aprilpass')
user4 = User.create(username: 'Whit', email: 'whit@me.com', password: 'whitpass')
user5 = User.create(username: 'Alex', email: 'alex@me.com', password: 'alexpass')
user6 = User.create(username: 'Dana', email: 'dana@me.com', password: 'danapass')
user7 = User.create(username: 'Selena', email: 'selena@me.com', password: 'selenapass')
user8 = User.create(username: 'Raegan', email: 'raegan@me.com', password: 'raeganpass')
user9 = User.create(username: 'Elizabeth', email: 'elizabeth@me.com', password: 'elizabethpass')
user10 = User.create(username: 'coolguy64', email: 'coolguy64@me.com', password: 'supercool')

album1 = Album.create(artist: 'David Bowie', title: 'Station to Station', release_year: '1976', genre: 'Rock')
album2 = Album.create(artist: 'Onyx', title: 'All We Got Iz Us', release_year: '1995', genre: 'Hip Hop')
album3 = Album.create(artist: 'Unwound', title: 'Leaves Turn Inside You', release_year: '2001', genre: 'Punk')
album4 = Album.create(artist: 'Nick Drake', title: 'Pink Moon', release_year: '1972', genre: 'Folk')
album5 = Album.create(artist: 'Fugazi', title: 'Repeater', release_year: '1990', genre: 'Punk')
album6 = Album.create(artist: 'Joanna Newsom', title: 'Ys', release_year: '2006', genre: 'Folk')
album7 = Album.create(artist: 'Charles Mingus', title: 'The Black Saint and the Sinner Lady', release_year: '1963', genre: 'Jazz')
album8 = Album.create(artist: 'Bill Evans Trio', title: 'Waltz for Debby', release_year: '1961', genre: 'Jazz')
album9 = Album.create(artist: 'MF DOOM', title: 'Mm..Food', release_year: '2004', genre: 'Hip Hop')
album10 = Album.create(artist: 'King Crimson', title: 'Red', release_year: '1974', genre: 'Rock')
album11 = Album.create(artist: 'Bill Evans Trio', title: 'Sunday at the Village Vanguard', release_year: '1961', genre: 'Jazz')
album12 = Album.create(artist: 'David Bowie', title: 'Low', release_year: '1977', genre: 'Rock')
album13 = Album.create(artist: 'David Bowie', title: 'Low', release_year: '1977', genre: 'Rock')
album14 = Album.create(artist: 'David Bowie', title: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', release_year: '1972', genre: 'Rock')
album15 = Album.create(artist: 'David Bowie', title: 'Hunky Dory', release_year: '1971', genre: 'Rock')
album16 = Album.create(artist: 'Fugazi', title: 'Red Medicine', release_year: '1995', genre: 'Punk')
album17 = Album.create(artist: 'Joanna Newsom', title: 'Have One on Me', release_year: '2010', genre: 'Folk')
album18 = Album.create(artist: 'MF DOOM', title: 'Operation: Doomsday', release_year: '1999', genre: 'Hip Hop')
album19 = Album.create(artist: 'Charles Mingus', title: 'Blues & Roots', release_year: '1960', genre: 'Jazz')
album20 = Album.create(artist: 'Nick Drake', title: 'Five Leaves Left', release_year: '1969', genre: 'Folk')
album21 = Album.create(artist: 'Nick Drake', title: 'Bryter Layter', release_year: '1970', genre: 'Folk')
album22 = Album.create(artist: 'King Crimson', title: 'In the Court of the Crimson King', release_year: '1969', genre: 'Rock')

listing1 = Listing.create(condition: 'Near Mint', price: 19, notes: ['1st Pressing'], user_id: 1, album_id: 3)
listing2 = Listing.create(condition: 'Mint', price: 23, notes: nil, user_id: 2, album_id: 2)
listing3 = Listing.create(condition: 'Good', price: 14, notes: nil, user_id: 3, album_id: 4)
listing4 = Listing.create(condition: 'Very Good', price: 16, notes: ['Colored Vinyl'], user_id: 4, album_id: 6)
listing5 = Listing.create(condition: 'Good', price: 12, notes: nil, user_id: 5, album_id: 9)
listing6 = Listing.create(condition: 'Mint', price: 22, notes: nil, user_id: 1, album_id: 7)
listing7 = Listing.create(condition: 'Near Mint', price: 18, notes: ['Picture Disc'], user_id: 2, album_id: 10)
listing8 = Listing.create(condition: 'Poor', price: 4, notes: nil, user_id: 3, album_id: 4)
listing9 = Listing.create(condition: 'Very Good', price: 12, notes: ['Sealed'], user_id: 4, album_id: 11)
listing10 = Listing.create(condition: 'Poor', price: 6, notes: nil, user_id: 5, album_id: 19)
listing11 = Listing.create(condition: 'Near Mint', price: 18, notes: ['Promotional Release'], user_id: 6, album_id: 18)
listing12 = Listing.create(condition: 'Mint', price: 26, notes: nil, user_id: 7, album_id: 13)
listing13 = Listing.create(condition: 'Good', price: 13, notes: nil, user_id: 8, album_id: 12)
listing14 = Listing.create(condition: 'Very Good', price: 17, notes: ['Limited Run'], user_id: 9, album_id: 16)
listing15 = Listing.create(condition: 'Good', price: 10, notes: nil, user_id: 10, album_id: 9)
listing16 = Listing.create(condition: 'Mint', price: 25, notes: nil, user_id: 6, album_id: 21)
listing17 = Listing.create(condition: 'Near Mint', price: 19, notes: ['Import'], user_id: 7, album_id: 15)
listing18 = Listing.create(condition: 'Poor', price: 5, notes: nil, user_id: 8, album_id: 20)
listing19 = Listing.create(condition: 'Very Good', price: 17, notes: ['Sealed', '1st Pressing'], user_id: 9, album_id: 22)
listing20 = Listing.create(condition: 'Poor', price: 5, notes: nil, user_id: 10, album_id: 14)
